topic:
  - partitions: 108
  - replication-factor: 3

producer-props:
  - acks: 1
  - linger.ms: 10
  - compression.type: lz4
  - batch.size: 100000

kafka-producer-perf-test:
  - record-size: 1024
  - throughput: 60000
  - num-records: 54000000

kafka-consumer-perf-test:
  - messages: 53950000
  - timeout: 30000
  